hal/imxrt19xx: fix enet PLL clk0 enable
phoenix-rtos/phoenix-rtos-kernel pull request #601
Opened 2024-09-26 14:10 UTC by julianuziemblo

## Description
Fix _imxrt_ccmInitEnetPll to correctly enable clk0 of enet PLL.

## Motivation and Context
Enet PLL clk0 is enabled using bit 13 of CCM_ANALOG_PLL_ENET register, but the shift for `enclk0` was  12, which does not match the iMX RT106x RM.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: `armv7m-imxrt106x-evk`.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2024-09-27 09:14 UTC, nalajcie commented
`imxrt19xx`?

2024-10-02 14:32 UTC, agkaminski submitted a review, later dismissed

2024-10-02 16:27 UTC, nalajcie requested changes
please copy the full solution from `plo` (setting bypass while changing the PLL freqency)

2024-10-04 08:05 UTC, agkaminski approved these changes

2025-03-20 09:16 UTC, ziemleszcz approved these changes

2025-03-20 09:56 UTC, merged